theme: just-the-docs
title: Dojo
description: Dojo is a repository for registering, storing, and running data-science models.
source: docs
repository: adamgilg/dojo-docs


aux_links:
  "View Dojo on GitHub":
    - "//github.com/dojo-modeling"
